### ISSUE TITLE
dirty state lost after failed validation

### ISSUE THREAD

**Issue by javi1065** [codedance/jquery.AreYouSure#31]
Let's say I changed an input, the dialog shows up just fine if I try to leave the page. But if I click the save button and there's a falied validation (client o server side) then I try to leave the page the dialog does not show and let me leave the page. It's as it beleive  that the form is clean again.

**Comment by wphampton** [comment]
Just as an addendum, if you have your own custom form submit handler it may help you to have it defined *after* you initialize AYS.  Since AYS attaches its own submit handler to the form to remove the 'dirty' class on form submit, you will likely want yours defined after so you can reapply the 'dirty' class as @codedance described in the event of the form not passing your validation.

I had trouble until I realized my handler was defined before AYS was bound to the form, so no matter what I did in my own submit handler to get that 'dirty' class applied to the form the AYS submit handler would always come along afterwards and wipe it out.  The following worked for me:

```javascript
// Initialize/Bind AYS first
$('#myform').areYouSure();

// Custom form submit handler defined second
$('#myform').submit(function (event) {
    if (validation_fails) {
        $('#myform').trigger('checkform.areYouSure');
        event.preventDefault();
    }
});
```

Thanks for the great software @codedance

**Comment by codedance** [comment]
@wphampton Thanks for the clarification.  That's a good fine and I can see how this could easily happen. I think this is probably best addressed with some improved documentation.  (e.g. your code sample above).  Do you agree?  If so, I'll open an issue and make the change (or of course happy to accept a pull request :-)
